### ISSUE TITLE
Streamline script approvals

### ISSUE THREAD

**Issue by kohsuke** [jenkinsci/jenkinsfile-runner#14]
I wonder if it'd be nice if Jenkinsfile Runner can do something like the permissive mode of SELinux, where it runs your pipeline entirely and spit out the approvals it needed?

Jesse points out that https://plugins.jenkins.io/permissive-script-security would be an useful piece for that. I need to look into it.

**Comment by oleg-nenashev** [comment]
Permissive Script security has been described in https://github.com/jenkinsci/jenkinsfile-runner/issues/38 . Also, `1.0-beta-7` includes a new `--no-sandbox` flag which effectively disables Sandbox for the user.

I believe it is fixed now
