### ISSUE TITLE
[JENKINS-56269] - support Environment & Secrets

### ISSUE THREAD

**Issue by ndeloof** [jenkinsci/jenkinsfile-runner#15]
Considering jenkinsfile-runner as a tool to run a Pipeline on developer's workstation, before it get committed and ran by a classic Jenkins master, we miss ability to set Environment and Secrets.

My proposal is to rely on [configuration-as-code](github.com/jenkinsci/configuration-as-code-plugin) to describe in a concise, human-friendly way the set of tools / credentials / xx required for pipeline execution. jenkinsfile-runner would by default look for a `Jenkinsfile-master.yaml` aside the Jenkinsfile to run. This file can be committed side by side with the Jenkinsfile for easier reproducibility by teammates.

To avoid credentials stored in SCM in clear text, I propose to rely on a `Jenkinsfile-secrets` credentials file (comparable to docker-secrets, already supported by CasC). This file would be encrypted, the same way [CodeShip does](https://documentation.codeship.com/pro/builds-and-configuration/environment-variables/#encrypting-your-environment-variables), so it can be committed in SCM as well. When ran, jenkinsfile-runner would decrypt this file in memory and use it to configure the transient master and run pipeline.

I'm submitting this proposal as a github issue for initial feedback loop before I start writing some more concrete proposal as a doc in jenkinsfile-runner repository.

**Comment by marcellodesales** [comment]
@ndeloof 
Looking for the same... We have Jenkins BlueOcean in a Kubernetes Cluster and we'd like to have the secret to be just as described: pushed to the repo securely and being able to be used by build/deploy.

**Comment by fwilhe** [comment]
Thanks for this suggestion, @ndeloof. Since I'm interested in #18, I'd be very eager to try this out.

Is there already a way to try this out with the current version of the conf as code plugin?

**Comment by je-al** [comment]
FWIW, I've tried enabling the configuration-as-code plugin, and mirroring the contents of the config.xml that gets auto-generated when I run the runner without it, and it seems to just hang.
The behavior is similar to the one it displays when you don't install the workflow-aggregator plugin (have had this happen to me by mistake)

**Comment by oleg-nenashev** [comment]
The issue has been moved to Jenkins JIRA: https://issues.jenkins-ci.org/browse/JENKINS-56269 . I believe it is mostly addressed by JCasC, but there are still some integrations to be done
