### ISSUE TITLE
Package Jenkinsfile Runner CLI as a fat JAR

### ISSUE THREAD

**Issue by jozef-slezak** [jenkinsci/jenkinsfile-runner#171]
It would be great to package Jenkinsfile Runner as a fat JAR in addition to the ZIP file. It would simplify using it on other platforms.

See #170 for the context

**Comment by oleg-nenashev** [comment]
FAT JAR was released in https://github.com/jenkinsci/jenkinsfile-runner/releases/tag/1.0-beta-10 , thanks to @jainsahab! There are minor issue there which needs a Jenkins core fix: #193 , but it works well overall. @jozef-slezak it would be great if you could try it out:

https://repo.jenkins-ci.org/releases/io/jenkins/jenkinsfile-runner/jenkinsfile-runner/1.0-beta-10/jenkinsfile-runner-1.0-beta-10.jar for the CLI. It still needs plugins to be supplied externally tho, we need to add a plugin bundling logic later

**Comment by oleg-nenashev** [comment]
https://github.com/jenkinsci/plugin-installation-manager-tool for tool installation BTW

**Comment by oleg-nenashev** [comment]
#193 was released, so I believe this can be closed. See https://github.com/jenkinsci/jenkinsfile-runner/issues/248 for the Plugin Installation Manager Integration
