### ISSUE TITLE
Update Jenkins Core to 2.195+ and use BOM to define core dependencies

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/jenkinsfile-runner#174]
Jenkins 2.195 introduced Jenkins BOM which describes versions of libraries used inside Jenkins: https://github.com/jenkinsci/jenkins/pull/4150. It would be great to use this BOM inside Jenkinsfile runner so that there are less dependencies to be manually managed.

https://github.com/jenkinsci/plugin-pom/pull/229 provides some documentation about using it, there is also #143 which demonstrates usage of another BOM in this repo

**Comment by ImShakthi** [comment]
@oleg-nenashev I would work in this issue

**Comment by oleg-nenashev** [comment]
@ImShakthi sorry for not linking it properly, I have submitted a PR in https://github.com/jenkinsci/jenkinsfile-runner/pull/177 . It is on hold now pending decisions whether we go to the latest weekly now or wait for LTS and more BOM patches (e.g. Jetty is not available through it)

**Comment by ImShakthi** [comment]
@oleg-nenashev Thanks! No problem.

**Comment by jasonyavorsky** [comment]
@oleg-nenashev do you think this might get updated? It would be nice to use the jenkinsfile-runner with the current LTS version, which doesn't seem possible without this update.

**Comment by oleg-nenashev** [comment]
Yes, I plan to get it over the line. Will likely go straight to 2.222 which is a new LTS baseline

**Comment by jasonyavorsky** [comment]
Amazing, thank you!

**Comment by oleg-nenashev** [comment]
https://github.com/jenkinsci/jenkinsfile-runner/pull/177 was merged, and I hope to release the new version this week
