### ISSUE TITLE
Add `--help` CLI argument which prints help

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/jenkinsfile-runner#179]
Currently the only way to get help is to pass invalid command. It would be great to support `-h` and `--help` in Jenkinsfile Runner CLI.

**Comment by ImShakthi** [comment]
@oleg-nenashev I would like to work on this enhancement

**Comment by oleg-nenashev** [comment]
@ImShakthi 👍 Just submit a pull request, thanks!

**Comment by ImShakthi** [comment]
@oleg-nenashev Have created a PR #183 for this issue. Kindly let me know your feebacks.

**Comment by oleg-nenashev** [comment]
Should be released soon

**Comment by ImShakthi** [comment]
@oleg-nenashev Thank you :)

**Comment by oleg-nenashev** [comment]
It was released in https://github.com/jenkinsci/jenkinsfile-runner/releases/tag/1.0-beta-10 . Thanks you for your contribution!
