### ISSUE TITLE
Serverless "one-shot" masters

### ISSUE THREAD

**Issue by ndeloof** [jenkinsci/jenkinsfile-runner#18]
On a large Jenkins deployment one might want to offload jenkins master to some "side" masters for pipeline execution. 

We could rely on jenkinsfile-runner for such a "one-shot" master, applying https://github.com/kohsuke/jenkinsfile-runner/issues/15 for configuration with adequate configuration scoped to a specific job, and on completion sync back build results to the main jenkins master (comparable to [build-publisher plugin](https://wiki.jenkins.io/display/JENKINS/Build+Publisher+Plugin)).
 
A full featured implementation would require some architecture effort for jenkins to be a cloud-native citizen, but it sounds to me we could rely on jenkinsfile-runner to demonstrate such a deployment and check interest for community in this direction.

cc @carlossg

**Comment by fwilhe** [comment]
I'm very interested in such an effort. Is there any progress on this, or any 'central' place where this is discussed?

**Comment by ndeloof** [comment]
best place to discuss this is jenkins-dev mailing list.

**Comment by fwilhe** [comment]
I've used this successfully to run our Jenkins pipeline on travisci, and I've described the how and the why [here](https://blogs.sap.com/2019/02/11/deep-dive-experimental-serverless-cicd-with-sap-s4hana-cloud-sdk-continuous-delivery-toolkit/).

**Comment by oleg-nenashev** [comment]
I believe this is completed. Tooling is provided by [Custom WAR Packager](https://github.com/jenkinsci/custom-war-packager)

* https://jenkins.io/blog/2018/09/12/speaker-blog-a-cloud-native-jenkins/
* https://jenkins.io/blog/2018/10/16/custom-war-packager/#jenkinsfile-runner-packaging

**Comment by oleg-nenashev** [comment]
Closing since there is no negative response about the suggestion above. 

Demo in this repo: https://github.com/jenkinsci/jenkinsfile-runner/tree/master/demo/cwp
