### ISSUE TITLE
Add a CLI flag to print Jenkinsfile Runner version

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/jenkinsfile-runner#180]
Currently there is no CLI argument which would print a Jenkinsfile Runner version. It would be great to have one, e.g. `-v` and `--version`

**Comment by mvarendorff** [comment]
Would love to do this! Could you give me a suggestion where to look for the flags?

The only place I found where CLI flags seem to be configured was the Bootstrap.java file which already contains an entry for -v/--version [here](https://github.com/jenkinsci/jenkinsfile-runner/blob/master/bootstrap/src/main/java/io/jenkins/jenkinsfile/runner/bootstrap/Bootstrap.java#L44). Is that the correct place? In that case would you suggest using a different name for the flag (and which)?

**Comment by oleg-nenashev** [comment]
Uh oh, so we have an argument collision :( My preference would be to
introduce a breaking change while we are in Beta. The existing param could
be renamed to "-jenkinsVersion" or so.

**Comment by Apoorv-Gaurav-Agarwal** [comment]
is this still available?

**Comment by oleg-nenashev** [comment]
No, sorry. #182 has implemented it. I will make sure to create more issues today

**Comment by oleg-nenashev** [comment]
It was released in https://github.com/jenkinsci/jenkinsfile-runner/releases/tag/1.0-beta-10 , thanks!
