### ISSUE TITLE
Create a Java/Maven demo based on the Vanilla package

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/jenkinsfile-runner#188]
Since we have `jenkins4eval/jenkinsfile-runner` up and running again, it would be great to have a small demo demonstrating the Docker image override

- [ ] - Demo includes Dockerfile which is based on the  `jenkins4eval/jenkinsfile-runner` image
- [ ] - Dockerfile install Maven (JDK is already bundled)
- [ ] - There is a Jenkinsfile which checks out a small hello-world sample repo and builds/tests it inside Jenkinsfile Runner
- [ ] - There is a README file in the demo which describes how to build/run the demos

**Comment by anthonydahanne** [comment]
~~you meant `jenkinsci/jenkinsfile-runner` , right ?~~ ah, I found out you meant the Docker image coordinates for https://hub.docker.com/r/jenkins4eval/jenkinsfile-runner

**Comment by oleg-nenashev** [comment]
As a repo - yes. But it is hosted as jenkins4eval/jenkinsfile-runner on
DockerHub now

**Comment by tinypulse-juanma** [comment]
the image is no longer available in dockerhub?

**Comment by oleg-nenashev** [comment]
It is here: https://hub.docker.com/r/jenkins4eval/jenkinsfile-runner

**Comment by tinypulse-juanma** [comment]
> It is here: https://hub.docker.com/r/jenkins4eval/jenkinsfile-runner

wow, not sure why but yesterday it was redirecting to the homepage, weird. Let's see if I can help with the task :)

**Comment by oleg-nenashev** [comment]
I created #218 as a part of the today;s hackathon

**Comment by oleg-nenashev** [comment]
More demos can be still created
