### ISSUE TITLE
Include Plugin Management Scripts into the Vanilla image

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/jenkinsfile-runner#190]
Eventiually I would like to make `jenkins4eval/jenkinsfile-runner` extensible in classic Docker ways, and plugin management is one of the common features there. The image used to include the plugin management scripts to include Declarative Pipeline, but it was removed in https://github.com/jenkinsci/jenkinsfile-runner/pull/187 .

It would be nice to restore bundling of plugin management scripts into the image. Then it can be documented for #189

**Comment by wpater** [comment]
@oleg-nenashev To clarify - we want to add `install-plugins.sh` to image to support `plugin.txt` file and plugins already added by maven move to this file, right?

**Comment by oleg-nenashev** [comment]
@wpater Right. It might be also interesting to add https://github.com/jenkinsci/plugin-installation-manager-tool instead of the CLI tool. We can allow such experiment in this image, because the tool will land in the main image at some point. CC @stopalopa @slide
