### ISSUE TITLE
Jenkinsfile Runner should fail immediately when running on an unsupported Jenkins version

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/jenkinsfile-runner#191]
`jenkins.version` in pom.xml actually defines the minimum supported Jenkins version. But this version is not really checked anywhere, and JFR run may fail randomly. It would be nice to verify the Jenkins version before staring execution.

Jenkins WAR file includes the Jenkins core version in its properties: https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/jenkins/model/Jenkins.java#L5057-L5066 . The code can be copied from there

It is a follow-up to https://github.com/jenkinsci/jenkinsfile-runner/issues/170

**Comment by glefloch** [comment]
Hi! I would like to work on this :)

**Comment by oleg-nenashev** [comment]
just do it :)

**Comment by glefloch** [comment]
Regarding this issue, could you give me some hint? the version is currently in the `pom.xml` file, as this won't be available in the war, where should I add it?

**Comment by oleg-nenashev** [comment]
@glefloch sorry, missed the comment. https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/jenkins/model/Jenkins.java#L5057-L5066 is a good example of how to access the data from WAR. Also, if `--jenkinsVersion` is specified, you could just compare with that.

The required Jenkins version can be retrieved from Properties using the same approach as in #180
