### ISSUE TITLE
Add Pipeline Utility Steps to the Vanilla Package

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/jenkinsfile-runner#196]
https://plugins.jenkins.io/pipeline-utility-steps is widely used for operations like YAML processing, and it would be great to have it as a part of the default package so that users do not need to extend the image just to get this plugin installed. 

Acceptance criteria:

* The plugin dependency is added to the bundle. Version can be taken from BOM
* There is a demo created which demonstrates how to use the plugin inside Jenkinsfile Runner
  * Demo from https://docs.google.com/presentation/d/1y7YnAdnh5WY59g8oIGTsj8sLQ5KXgoV7uUCBkxcTU88/edit?usp=sharing can be used for it:

```groovy
stage('Read Evergreen YAML') {
    node {
        // Discover core version using Pipeline utility steps
        sh 'wget https://raw.githubusercontent.com/jenkins-infra/evergreen/master/services/essentials.yaml'
        def essentialsYaml = readYaml(file: "essentials.yaml")
        echo "Jenkins Evergreen uses the following Core version: ${essentialsYaml.spec.core.version}"
    }
}
```

**Comment by rajovictor** [comment]
Hi @oleg-nenashev,
I was able to run the above `Jenkinsfile` by adding `pipeline-utility-steps` dependency to the **vanilla-package** `pom.xml`.
I believe, the bom entry is maintained in another repo.
Also, I had to add explicit `org.apache.commons:commons-lang3:3.7` dependency since the `org.apache.maven.plugins.enforcer.RequireUpperBoundDeps` was failing the build otherwise.

Please let me know if those pom changes would be eligible for a PR to solve this issue.

**Comment by oleg-nenashev** [comment]
Hi @rajovictor , thanks for your Interest! This issue was actually solved in #200 which was integrated recently. 

> Also, I had to add explicit org.apache.commons:commons-lang3:3.7 dependency since the org.apache.maven.plugins.enforcer.RequireUpperBoundDeps was failing the build otherwise.

This is something we will need to address later, because the dependency comes from the Jenkins core. It does not appear in #200 because of the dependency inclusion order, but the risk is still there. If yu are interested to create a pull request for it on the top of the current branch, it will be much appreciated

**Comment by rajovictor** [comment]
> Hi @rajovictor , thanks for your Interest! This issue was actually solved in #200 which was integrated recently.
> 
> > Also, I had to add explicit org.apache.commons:commons-lang3:3.7 dependency since the org.apache.maven.plugins.enforcer.RequireUpperBoundDeps was failing the build otherwise.
> 
> This is something we will need to address later, because the dependency comes from the Jenkins core. > It does not appear in #200 because of the dependency inclusion order, but the risk is still there. If yu >are interested to create a pull request for it on the top of the current branch, it will be much appreciated

You mean a PR with explicit `org.apache.commons:commons-lang3:3.7` dependency to the `vanilla-package` pom or the `jenkinsfile-runner` pom?

**Comment by oleg-nenashev** [comment]
> You mean a PR with explicit org.apache.commons:commons-lang3:3.7 dependency to the vanilla-package pom or the jenkinsfile-runner pom

If it is a real concern, it has to be in root POM to prevent classloading issues. https://github.com/jenkinsci/jenkinsfile-runner/pull/177 should eventually solve it by forcing Jenkins core versions

**Comment by oleg-nenashev** [comment]
Closing this issue to indicate the acceptance criteria is completed.
@rajovictor please feel free to follow-up as discussed above. GitHub issue is not needed unless you want to create one
