### ISSUE TITLE
Add support of Job Names with folders

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/jenkinsfile-runner#210]
#203 added support of arbitrary Job names, but it is not possible to set a folder using the current approach. It would be great to add support of nested paths like `folder1/folder2/job1` so that users of Jenkinsfile Runner can emulate standard Jenkins structures more easily.

CC @rinckm  @alxsap

**Comment by glefloch** [comment]
Would like to give it a try!

**Comment by glefloch** [comment]
@oleg-nenashev, after looking at the code, it seems like this does not allow for folders.    

    Jenkins.checkGoodName(bootstrap.jobName); 

Would removing this be enough ?

**Comment by oleg-nenashev** [comment]
I would rather create a virtual folder structure inside the JFR runtime.
It is not just enough to have an item with slashes to emulate folders for
some Jenkins plugins

**Comment by rinckm** [comment]
Also environment variable JOB_BASE_NAME should work correctly in the pipeline.

**Comment by sladyn98** [comment]
I was just going through the issue @oleg-nenashev The above PR seems to have closed this issue, is there something pending here ?

**Comment by oleg-nenashev** [comment]
I do not think so @sladyn98 . There are definitely some possible improvements (e.g. for multibranch), but they can be handled separately. Thanks to @addihorn for the patch!
