### ISSUE TITLE
Allow passing a compressed WAR file in the '--war' argument

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/jenkinsfile-runner#224]
Currently `--war` option takes a part to the unzipped WAR file directory. Although it is good from the performance point of view, it causes confusion since Jenkinsfile Runner shows an odd behavior (classloading failures) when a WAR file is passed.

I suggest the following behavior:

* If a WAR file is passed, Jenkinsfile Runner automatically unpacks it to a temporary directory OR to a work directory.
** In the case of the work directory (sharing between runs), a checksum should be calculated and persisted somehow to avoid collisions when a source war is changed. Such caching is not mandatory IMHO
* When the option points to a WAR instead of the folder, a warning is printed to indicate the performance implications (WAR unpacking)

CC @btk3000

**Comment by freemwil** [comment]
Is this still available?
