### ISSUE TITLE
Build instructions?

### ISSUE THREAD

**Issue by finchr** [jenkinsci/jenkinsfile-runner#232]
Nice tool, it's really helped me troubleshoot my Jenkinsfile. However, there is a noticeable lack of build instructions in the repo. Lot's of stuff on how to use it but nothing on how to build it. I was able to successfully reverse engineer the build process on my mac from the Dockerfile but a build or installation section in the documentation would be nice.

**Comment by oleg-nenashev** [comment]
If we talk about the vanilla image in this  repo, the build process boils down to `mvn clean package`. Custom package build is less trivial, but there are demos included

**Comment by ibrf** [comment]
> If we talk about the vanilla image in this repo, the build process boils down to `mvn clean package`. Custom package build is less trivial, but there are demos included

I got that from the Dockerfile, but that doesn't say anything about dependencies (openjdk 8?) or steps to actually get the jenkinsfile-runner script installed and functioning on the system.

**Comment by oleg-nenashev** [comment]
https://github.com/jenkinsci/jenkinsfile-runner/blob/master/CONTRIBUTING.md#getting-started now includes prerequisites for build tools.
