### ISSUE TITLE
Doesn't support @Library annotations

### ISSUE THREAD

**Issue by cfurst** [jenkinsci/jenkinsfile-runner#247]
When running a jenkinsfile that has a `@Library` declaration, after configuring global plugins and declaring a global Pipeline library in the Jenkins instance, jenkinsfile-runner fails:
```groovy
WorkflowScript: 2: unable to resolve class Library ,  unable to find class for annotation
 @ line 2, column 1.
   @Library('libname') _
```
To reproduce:
1. Follow the setup instructions as per README.md and install plugins
1. in the Jenkins instance `localhost:8080` go to `Manage Jenkins` select `Global configuration`
1. configure the `Global Pipeline Library` section to be able to pull down from an SCM a library repository
1. Add an `@Library` annotion to a jenkinsfile that you with to run pointing to the global library you defined above
1. Run `jenkinsfile-runner -w $JENKINS_HOME -p $JENKINS_HOME -f path/to/Jenkinsfile_with_anotation`

**Comment by cfurst** [comment]
Duplicated and known

**Comment by shadycuz** [comment]
is this fixed?
