### ISSUE TITLE
Replace jsr-305 annotations by SpotBugs ones

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/jenkinsfile-runner#296]
Similarly to https://github.com/jenkinsci/jenkins/pull/4604 , we should remove JSR annotations and use ones supplied by SpotBugs.

It should also help towards building JFR with JDK 11, see https://github.com/jenkinsci/jenkinsfile-runner/pull/231

**Comment by devkonarev** [comment]
Hi, I will give it a go.
