### ISSUE TITLE
Replace "Hudson" by "Jenkins" in the codebase

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/jenkinsfile-runner#375]
There is some old Jenkinsfile Runner code which was originally a part of Jenkins test frameworks. This code uses the "Hudson" name though Jenkins was renamed to Hudson in 2011. It would be great to cleanup this code. Some occurences: https://github.com/jenkinsci/jenkinsfile-runner/search?q=Hudson

Acceptance criteria:

* "Hudson" occurrences in the documentation, Javadoc and comments are replaced with Jenkins
* "Hudson" occurrences in class and method names are replaced by "Jenkins". In this repository binary compatibility is not a concern even for public classes

**Comment by darkphoenix17** [comment]
I can work on it.

**Comment by darkphoenix17** [comment]
Should only the occurence in the search result be replaced?
I am new to the open source world and want to start.
An assistance would be very helpful.

**Comment by oleg-nenashev** [comment]
@darkphoenix17 GitHub search is not ideal. If you see occurrences in other places, please feel free to update them as well. Same can be done for other Jenkins components, though you need to be more careful about API changes in them.

**Comment by darkphoenix17** [comment]
Okay, I am making a PR with the necessary changes. Guide me if I am wrong somewhere, please.
