### ISSUE TITLE
Scripts not permitted to use staticMethod

### ISSUE THREAD

**Issue by navi86** [jenkinsci/jenkinsfile-runner#38]
Hello, 
I got error during running pipeline 
Scripts not permitted to use staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods
How to fix this issue fr jenkinsfile-runer ?

**Comment by oleg-nenashev** [comment]
1) Whitelist the method. E.g. via JCasC once https://github.com/jenkinsci/script-security-plugin/pull/219 is done
2) Install the Permissive Script Security Plugin and disable sandbox (not recommended)

**Comment by navi86** [comment]
I’ve installed plugin, but I can’t figure it out how to enable it because there is no file jenkins.xml. 
`The plugin is disabled after installation. It can be enabled providing -Dpermissive-script-security.enabled=true property to Jenkins master JVM. Since 0.3, value no_security is supported to permit not whitelisted signatures without any logging. Note that this is not secure at all`

**Comment by oleg-nenashev** [comment]
> It can be enabled providing -Dpermissive-script-security.enabled=true property to Jenkins master JVM

You need to pass a system property

**Comment by navi86** [comment]
> > It can be enabled providing -Dpermissive-script-security.enabled=true property to Jenkins master JVM
> 
> You need to pass a system property

I am sorry, but I don't know how to do it, because jenkinsfile-runner execute Jenkins...so How to do it ?

**Comment by uridium** [comment]
Could you shed some light on passing JVM params to Jenkins master or whitelisting methods?
I'm having the same problem.

**Comment by ReddyKilowatt** [comment]
We keep running into this, but seems like it only happening when we use Container folders.
I can't say I understand the suggested fixes (especially this -> 2\. Install the Permissive Script Security Plugin and disable sandbox (not recommended) ), I'm very new to Jenkins.

**Comment by piotrbrzuska** [comment]
@uridium , @ReddyKilowatt:

first install `Permissive Script Security Plugin`

after build jenkinsfile-runner by mvn edit( or create copy and edit new one) file `app\target\appassembler\bin\jenkinsfile-runner` (or jenkinsfile-runner.bat for Windows).
Then add parameter ` -Dpermissive-script-security.enabled=true` do line which start with `%JAVACMD% %JAVA_OPTS%  `.

**Comment by oleg-nenashev** [comment]
https://github.com/jenkinsci/jenkinsfile-runner/pull/26 has been released in `1.0-beta-7` (Changelog is coming soon). With this update you can use the `--no-sandbox` flag to disable sandboxing in Jenkinsfile Runner without complex solutions.

Closing this ticket, please feel free to reopen if anything left to be done here
