### ISSUE TITLE
How to access a local Powershell file from a Jenkins pipeline Project

### ISSUE THREAD

**Issue by jamestechv** [jenkinsci/jenkinsfile-runner#441]

**Comment by oleg-nenashev** [comment]
Hello. Please use proper channels like https://groups.google.com/forum/#!forum/jenkinsci-users to ask questions. This is an issue tracker of the Jenkinsfile Runner component, and it does not look like this issue is related to Jenkinsfile Runner.

**Comment by jamestechv** [comment]
Sorry for the inconvenience caused, please delete my issue if possible ,Thanks

**Comment by oleg-nenashev** [comment]
Hi, no worries!
