### ISSUE TITLE
Failed loading plugins with "Jenkins (2.263) or higher required" error

### ISSUE THREAD

**Issue by Nezz** [jenkinsci/jenkinsfile-runner#442]
Running pipelines fails with the following error:
```
SEVERE	jenkins.InitReactorRunner$1#onTaskFailed: Failed Loading plugin Pipeline: Basic Steps v2.23 (workflow-basic-steps)
java.io.IOException: Failed to load: Pipeline: Basic Steps (2.23)
 - Jenkins (2.263) or higher required
	at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:952)
	at hudson.PluginManager$2$1$1.run(PluginManager.java:549)
	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1131)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
Which is followed by cascading plugin loading errors.

Versions:
- Jenkins 2.263.1
- Jenkinsfile-runner 1.0-beta-22

I found [this ticket](https://issues.jenkins.io/browse/JENKINS-56858) about a similar error. Is the Jenkins version of the war not picked up correctly jenkinsfile-runner? 

Steps to reproduce:
1. Execute the following:
```
wget -O jenkinsfile-runner.jar https://github.com/jenkinsci/jenkinsfile-runner/releases/download/1.0-beta-22/jenkinsfile-runner-1.0-beta-22.jar
wget http://mirrors.jenkins.io/war-stable/latest/jenkins.war
unzip jenkins.war -d jenkins

export JENKINS_HOME=jenkins_home
java -jar jenkins.war
```
2. Go to http://localhost:8080/ and install the suggested set of plugins.
3. Run the pipeline:
```
java -jar jenkinsfile-runner.jar -w jenkins -p jenkins_home/plugins -f Jenkinsfile
```

**Comment by oleg-nenashev** [comment]
@Nezz I think you have installed latest plugins using the recent Jenkins versions. Jenkinsfile Runner uses 2.249.x under the hood, and not all recent plugin versions are compatible with it. I would recommend using https://github.com/jenkinsci/plugin-installation-manager-tool for downloading plugins, you can specify explicit versions there and do compatibility checks.

The next Jenkinsfile Runner release will be base on 2.263.1, ETA is this weekend

**Comment by Nezz** [comment]
Thanks, I'll wait for the next release then. I just followed the [docs](https://github.com/jenkinsci/jenkinsfile-runner#preparation) which instructed me to get the latest version of Jenkins.

**Comment by Nezz** [comment]
Looks like the stable version used by the instructions was updated to 2.263 yesterday, hence this issue.

**Comment by oleg-nenashev** [comment]
Yeah, these instructions need to be updated. Thanks for the clarification!
if you just want to try out Jenkinsfile Runner, my recommendation would be to use the Docker image which already includes many common plugins

**Comment by oleg-nenashev** [comment]
The new release is on 2.263.x . I have also updated the README a bit.
Please feel free to reopen if anything else is needed in this ticket
