### ISSUE TITLE
Add an option to wait upon completion

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/jenkinsfile-runner#553]
@rsvoboda added a lovely feature for automatically opening the Web UI in https://github.com/jenkinsci/jenkinsfile-runner/pull/552 . It might be useful to also keep Jenkinsfile Runner running upon job completion without various `sleep()` hacks in the Pipeline. Then Jenkinsfile Runner users will be able to take their time, e.g. to browse reports

Expectations:

* Add a new boolean CLI parameter, e.g. `waitOnExit`
* If the option is set, Jenkinsfile Runner waits upon the payload task completion BUT before the tear down phase
* The execution can be interrupted by CLI (e.g. pressing a button or a signal like SIGINT), or by a root action in the Web UI

**Comment by rsvoboda** [comment]
Not sure if new option is needed, `command.launcherOptions.openWebUI && command.launcherOptions.httpPort != null` could be checked instead

Is || || || something which could be good enough for this of you are expecting something to handle signals etc.?
&nbsp;&nbsp;&nbsp; v v v

```diff
diff --git a/setup/src/main/java/io/jenkins/jenkinsfile/runner/JenkinsLauncher.java b/setup/src/main/java/io/jenkins/jenkinsfile/runner/JenkinsLauncher.java
index 416bc09..6ac7036 100644
--- a/setup/src/main/java/io/jenkins/jenkinsfile/runner/JenkinsLauncher.java
+++ b/setup/src/main/java/io/jenkins/jenkinsfile/runner/JenkinsLauncher.java
@@ -13,6 +13,7 @@ import java.io.File;
 import java.io.IOException;
 import java.net.URISyntaxException;
 import java.util.EnumSet;
+import java.util.concurrent.TimeUnit;
 import java.util.logging.Level;
 import java.util.logging.Logger;
 import javax.servlet.DispatcherType;
@@ -189,6 +190,15 @@ public abstract class JenkinsLauncher<T extends JenkinsLauncherCommand> extends

     @Override
     public void after() throws Exception {
+        if (command.launcherOptions.openWebUI && command.launcherOptions.httpPort != null) {
+            try {
+                while (true) { // keep the WebUI up and running
+                    TimeUnit.MILLISECONDS.sleep(500);
+                }
+            } catch (InterruptedException ie) {
+                Thread.currentThread().interrupt();
+            }
+        }
         if (command.launcherOptions.skipShutdown) {
             // Skips the clean up. This was initially motivated by SLF4J leaving gnarly messages.
             // The whole JVM is going to die anyway, but without the cleanup the Jenkins termination logic won't be invoked
```

root action in the Web UI ... that means calling http://localhost:8080/exit or http://localhost:8080/safeExit? Because in "Manage Jenkins" section I could see only "prepare for shutdown", but no shutdown button.

**Comment by rsvoboda** [comment]
@oleg-nenashev can you pls comment on ^^^?

**Comment by oleg-nenashev** [comment]
I would rather add another option. There are use cases when you need web UI but do not need the instance to stay active upon completion

Examples:

* input() step when a user goes to the UI, checks reports and makes the decision whether the pipeline should be continued
* HTTP port but only for inbound agents connection. I believe this is the use case for @agentgonzo and @abayer

**Comment by rsvoboda** [comment]
OK, another option sounds right with these details.

What about proposed wait loop, is it fine or would you prefer something else?

**Comment by oleg-nenashev** [comment]
As long as it gets interrupted by system signals, it is fine IMHO
