### ISSUE TITLE
Update the JDK and Jenkins Core to the latest versions

### ISSUE THREAD

**Issue by pandaasu** [jenkinsci/jenkinsfile-runner#641]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Using Azure VM with following specifications
-	OS : Windows server 2019 or 2022 
-	Core : 4
-	Memory : 16 GB

### Reproduction steps

Even a basic pipeline isn't getting kicked off because few of the plugins are demanding latest version of JDK or latest version of Jenkins Core. Along with this, the script for linux provides many features more than the windows one and our runner is a Windows, so please add the latest features and versions support for windows too.

Here I am  leaving a copy of my codebase here for reference - [jfr_setup](https://github.com/pandaasu/jfr_setup)

### Expected Results

The expecetd result was the same as  the screenshot provided in the README file of Jenkinsfilerunner. We have modified many things by far within a week but we are getting many errors one after another because of the version issues. Here I am sharing a short piece of log
`WARNING	o.j.p.workflow.graph.FlowNode#persistSafe: failed to save actions for FlowNode id=2
java.lang.reflect.InaccessibleObjectException: Unable to make field private static final long java.lang.Throwable.serialVersionUID accessible: module java.base does not "opens java.lang" to unnamed module @[54](https://github.com/<Org-name>/bai_test_jfr_compatibility/runs/7739653449?check_suite_focus=true#step:3:55)f5f647
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:180)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:174)
	at com.thoughtworks.xstream.converters.reflection.FieldDictionary.buildDictionaryEntryForClass(FieldDictionary.java:176)
	at com.thoughtworks.xstream.converters.reflection.FieldDictionary.buildMap(FieldDictionary.java:142)
	at`

### Actual Results

Everytime we solve one issue regarding version another one pops up, so unable to share any particular issue. For the time being sharing the issues showed up the last time.

`WARNING	o.j.p.workflow.graph.FlowNode#persistSafe: failed to save actions for FlowNode id=2
java.lang.reflect.InaccessibleObjectException: Unable to make field private static final long java.lang.Throwable.serialVersionUID accessible: module java.base does not "opens java.lang" to unnamed module @[54](https://github.com/<Org-name>/bai_test_jfr_compatibility/runs/7739653449?check_suite_focus=true#step:3:55)f5f647
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:180)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:174)
	at com.thoughtworks.xstream.converters.reflection.FieldDictionary.buildDictionaryEntryForClass(FieldDictionary.java:176)
	at com.thoughtworks.xstream.converters.reflection.FieldDictionary.buildMap(FieldDictionary.java:142)
	at`

### Anything else?

- It's an sincere request to update the versions and release a new package if possible. If the underlying procedures to release a package then please provide the step by step guide on how to build package and use it locally, we will do the rest.
- Please improve the documentation according to linux/windows both and many more tiny bits of information like how plugins gets picked up, how to update the latest plugins, commands etc because it was tedious to internal architecture.
- Please add the steps on how to lunch the UI and use it properly.

Requesting help from the maintainers as well as @lucaspanjer @cris @cowboyd @vbehar @trondn @oleg-nenashev

Thanks

**Comment by oleg-nenashev** [comment]
It should land after https://github.com/jenkinsci/jenkinsfile-runner/pull/640

**Comment by lhupfeldt** [comment]
#640 is merged, is anything else blocking a new release?
This is preventing us from testing with the same versions that we use in our Jenkins deployments.

**Comment by oleg-nenashev** [comment]
Nothing was blocking except me being underwater with the personal and work stuff. I will try to release it ASAP

**Comment by lhupfeldt** [comment]
A colleague of mine just reported a plugin compatibility issue.
I told him to wait for this.
Is there anything we can do to assist?

**Comment by oleg-nenashev** [comment]
@lhupfeldt good question. I think we should be okay, will try to release in the coming days.
The project needs more contributors and co-maintainers

**Comment by lhupfeldt** [comment]
@oleg-nenashev Any ETA on the release?

**Comment by lhupfeldt** [comment]
@oleg-nenashev Any issues with the release? Can we help?

**Comment by thiagosanches** [comment]
looking forward for this!

**Comment by mcambal** [comment]
same here, it becomes a blocking issue. I am sure, we all don't want pushing you @oleg-nenashev and understand you have other activities, but It would be good to clearly know whether this repository is abandoned or not.  It is important to know, if we should take actions to find a different solution or this repo is a perspective long-term solution. If yes, the regular upgrade and maintenance plan is the basic requirement.

What are your thoughts on this?

**Comment by oleg-nenashev** [comment]
@mcambal The repository is not abandoned but I've been on a long sabbatical as it was announced in the developer mailing list and other channels (war in Ukraine, parenting and other personal reasons). I'm always interested in having co-maintainers, and everyone is welcome to participate in this project

Going back to the issue, it should be somewhat addressed in https://github.com/jenkinsci/jenkinsfile-runner/releases/tag/1.0-beta-31 . There are likely many issues with the release, and everyone is welcome to test it out and to share their feedback. Please reopen this issue if it does not work for your use-case
