### ISSUE TITLE
Demo docs have out of date container image names

### ISSUE THREAD

**Issue by johnandersen777** [jenkinsci/jenkinsfile-runner#650]
### Jenkins and plugins versions report

- https://github.com/jenkinsci/jenkinsfile-runner/tree/main/demo
- https://github.com/jenkinsci/jenkinsfile-runner/blob/8fb1b688719218bb95b609caa0700467a6be1d09/demo/pipeline-as-yaml/README.md

### What Operating System are you using (both controller, and any agents involved in the problem)?

N/A

### Reproduction steps

N/A

### Expected Results

N/A

### Actual Results

N/A

**Comment by shadycuz** [comment]
@pdxjohnny  Seems like this can be closed?

**Comment by oleg-nenashev** [comment]
I think so. I will be doing a considerable demo revamp anyway
