### ISSUE TITLE
Update the roadmap

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/jenkinsfile-runner#659]
### Describe your use-case which is not covered by existing documentation.

The GitHub project was moved to https://github.com/orgs/jenkinsci/projects/22 as a part of the GitHub Projects 2.0 update. There is no automatic redirect. All the links need to be updated - documentation, badges, etc.

**Comment by dotSlash-Adwitiya** [comment]
Hello, I want to get started with open-source. And I am exploring all the jenkin projects. I know java and spring at a beginner level. Can you please help me with what changes I can make and start contributing?

**Comment by Abhishekverma2002** [comment]
Please assign me this issue. I am willing to continue onto this. Also tell me in which folder to make change. @oleg-nenashev @

**Comment by ashuoooo** [comment]
Hello folks I just want to contribute in google summer code. So suggest me best good first issues to best contribute.

**Comment by VignanMudedla** [comment]
hey @oleg-nenashev looks like you have solved this issue in your PR  #682 
It's been open for around 2 months. Can you close this good-first-issue because I just went to make these changes since the Issue is open. It might be bit confusing for the new-comers to find weather someone actually made changes or not

**Comment by oleg-nenashev** [comment]
Ok, will do. Sorry, I'm a little bit behind scrub and call my projects after a long sabbatical

**Comment by VignanMudedla** [comment]
> Ok, will do. Sorry, I'm a little bit behind scrub and call my projects after a long sabbatical

In-front of your great work it's a common thing to forget. No sorry needed.

@oleg-nenashev  I'm new to Jenkins and open-source, I just know java. I've just made changes for modernising plugins by watching the tutorial of Mark but, I'm not able to understand the code and I feel the barrier of entry in code contributions. Can you share how to get started with code contributions for a beginner (what are the prerequisites to learn/ skills needed) to contribute to Jenkins. I searched a lot in the Jenkins.io and Jenkins YouTube channel for help but I'm not able to find any resources. Can you share some resources. It'd be great if you make a tutorial on  "How a beginner can contribute to Jenkins". it'd be a great help for beginners

**Comment by oleg-nenashev** [comment]
FWIW, there are plenty of tutorials for newcomer contributors.
See https://www.jenkins.io/participate/ to get started

**Comment by oleg-nenashev** [comment]
P.S: I updated the links in 1.0-beta-32
