### ISSUE TITLE
1.0-beta-31 - ClassNotFoundException: org.eclipse.jetty.util.thread.ThreadPool

### ISSUE THREAD

**Issue by lhupfeldt** [jenkinsci/jenkinsfile-runner#686]
### Jenkins and plugins versions report

The Caused by: java.lang.ClassNotFoundException: org.eclipse.jetty.util.thread.ThreadPool is not specifically related to the docker image as mentioned here #657, it also happens when using jenkins.war with 1.0-beta-31.

Tried a few combinations, including:

]$ java --version
openjdk 11.0.18 2023-01-17
OpenJDK Runtime Environment (Red_Hat-11.0.18.0.10-1.fc37) (build 11.0.18+10)
OpenJDK 64-Bit Server VM (Red_Hat-11.0.18.0.10-1.fc37) (build 11.0.18+10, mixed mode, sharing)

]$ java --version
openjdk 17.0.6 2023-01-17
OpenJDK Runtime Environment (Red_Hat-17.0.6.0.10-1.fc37) (build 17.0.6+10)
OpenJDK 64-Bit Server VM (Red_Hat-17.0.6.0.10-1.fc37) (build 17.0.6+10, mixed mode, sharing)

JENKINS_VERSION = "2.375.3"
PLUGIN_MANAGER_VERSION = "2.12.11"
JENKINSFILE_RUNNER_VERSION = "1.0-beta-31"

Tried with no plugins and set of plugins working with 1.0-beta-30 and java 1.8.

### What Operating System are you using (both controller, and any agents involved in the problem)?

Linux  Fedora

### Reproduction steps

Get jenkinsfile-runner 1.0-beta-31and jenkins.war 2.375.3
execute runner

### Expected Results

jenkins start and executes specified pipeline as it did with previous version and old jenkins.war on java 8

### Actual Results

ClassNotFoundException: org.eclipse.jetty.util.thread.ThreadPool

**Comment by oleg-nenashev** [comment]
It is a valid defect, I think I will need to update Jetty and the Jenkins core even further

**Comment by jonesbusy** [comment]
Yes is broken since 2.361 LTS

Latest version that I was able to use is 2.346.3

`jfr-setup-action` GitHub action still reference 3.346.1 as default version : https://github.com/jenkinsci/jfr-setup-action/blob/master/action.yml#L6

**Comment by oleg-nenashev** [comment]
This one should be fixed now, kudos to @romanisb 
P.S: Co-maintainers are welcome in this project, I am still unable to dedicate enough time
